// Human-readable labels, kept in sync with backend/app/form_definitions.py

// Common identity fields the CIF collects (plus Aadhaar, which HR can fill in
// during document collection). Auto-carried into BGV / Document forms.
const PROFILE_FIELDS = [
  "full_name", "email", "contact_number", "alternate_number", "date_of_birth",
  "gender", "current_address", "permanent_address", "pan_number", "aadhaar_number",
];

// The rest of candidate_profiles. Not shown on the CIF card (the CIF never
// asks for them), but HR can open them for editing, so they need labels.
const PROFILE_EXTRA_FIELDS = [
  "highest_qualification", "university_name", "graduation_year",
  "bank_account_number", "bank_ifsc_code",
  "emergency_contact_name", "emergency_contact_number",
];

// Flat (one-value) fields per form — each is a column in its detail table.
const CIF_FIELDS = [
  "position_applied_for", "skills_technologies",
  "alternate_email", "blood_group", "linkedin_link", "marital_status",
  "any_backlogs", "source", "worked_in_levelshift_before",
  "total_experience_yrs", "relevant_skill_exp_yrs",
  "current_ctc_lpa", "expected_ctc_lpa", "additional_allowance",
  "variable_comp", "notice_period_days", "other_offers",
  "technical_certifications", "understanding_of_levelshift", "aspirations",
  "declaration_accepted", "declaration_place", "declaration_date",
  "hr_candidate_id", "hr_candidate_email",
];

const BGV_FIELDS = [
  "consent_bgv",
  "consent_criminal_check",
  "may_contact_current_employer",
  "name_as_per_records",
  "other_names_used",
  "passport_number",
  "passport_expiry",
  "driving_licence_number",
  "has_gaps",
  "ever_convicted",
  "conviction_details",
  "pending_case",
  "pending_case_details",
  "ever_terminated",
  "termination_details",
  "disciplinary_action",
  "disciplinary_details",
  "has_bond_noncompete",
  "bond_details",
  "dual_employment",
  "dual_employment_details",
  "declaration_accepted",
  "declaration_place",
  "declaration_date",
];

const DOC_FIELDS = [];  // Document Collection is uploads only

const FORM_FILE_FIELDS = {
  CIF: ["profile_picture", "signature"],
  BGV: ["signed_consent_form", "passport_copy_bgv", "form16_last_year", "form16_previous_year", "bank_statement_salary", "police_clearance_certificate", "bgv_signature"],
  DOCUMENT_COLLECTION: [
    "cc_offer_letter",
    "cc_role_change_letter",
    "cc_experience_letter",
    "cc_relieving_letter",
    "cc_pay_slips",
    "pc1_offer_letter",
    "pc1_role_change_letter",
    "pc1_experience_letter",
    "pc1_relieving_letter",
    "pc1_pay_slips",
    "pc2_offer_letter",
    "pc2_role_change_letter",
    "pc2_experience_letter",
    "pc2_relieving_letter",
    "pc2_pay_slips",
    "pc3_offer_letter",
    "pc3_role_change_letter",
    "pc3_experience_letter",
    "pc3_relieving_letter",
    "pc3_pay_slips",
    "pc4_offer_letter",
    "pc4_role_change_letter",
    "pc4_experience_letter",
    "pc4_relieving_letter",
    "pc4_pay_slips",
    "marksheet_10", "marksheet_12_diploma",
    "ug_consolidated_marksheet", "ug_certificate",
    "pg_consolidated_marksheet", "pg_certificate",
    "other_edu_marksheet", "other_edu_certificate",
    "additional_certifications",
    "passport_size_photo", "pan_card", "aadhar_card", "passport_copy",
    "address_proof", "id_proof",
  ],
};

// Repeating-row tables: table name (API) -> column order for display
const EDUCATION_COLUMNS = ["qualification", "course_college", "cgpa_percent", "year_of_passing", "has_marksheet", "gaps"];
const EMPLOYMENT_COLUMNS = ["company_name", "position_held", "from_date", "to_date", "currently_working",
                             "reason_for_leaving", "offer_letter", "relieving_letter_status", "experience_certificate", "gaps"];
const REFERENCE_COLUMNS = ["employee_name", "email_id", "technology", "experience", "contact_number"];


// BGV repeating verification sections
const BGV_TABLE_COLUMNS = {
  bgv_address_history: ["address_type", "full_address", "city", "state", "pin_code", "from_date", "to_date", "residence_type", "verifier_name", "verifier_contact", "nearest_police_station"],
  bgv_education_checks: ["qualification", "institution", "university_board", "roll_number", "registration_number", "year_of_passing", "study_mode", "verification_contact"],
  bgv_employment_checks: ["company_name", "company_address", "employee_id", "designation_joining", "designation_leaving", "from_date", "to_date", "employment_type", "payroll_company", "last_drawn_ctc", "manager_name", "manager_designation", "manager_email", "manager_phone", "hr_name", "hr_email", "hr_phone", "reason_for_leaving", "eligible_for_rehire", "may_contact_now"],
  bgv_reference_checks: ["name", "designation", "company", "relationship", "email", "phone", "years_known"],
  bgv_gaps: ["gap_type", "from_date", "to_date", "duration", "reason"],
};

const BGV_TABLE_TITLES = {
  bgv_address_history: "Address History",
  bgv_education_checks: "Education Verification",
  bgv_employment_checks: "Employment Verification",
  bgv_reference_checks: "Professional References",
  bgv_gaps: "Gaps in Education / Employment",
};

// Repeating sections, keyed the way the audit log names them
// ("education.course_college") and the grant list identifies them.
const ROW_TABLE_TITLES = {
  education: "Education",
  employment: "Employment",
  references: "References",
  bgv_address_history: "Address History",
  bgv_education_checks: "Education Verification",
  bgv_employment_checks: "Employment Verification",
  bgv_reference_checks: "Professional References",
  bgv_gaps: "Gaps",
};

const EDUCATION_SECTION_LABELS = {
  UG_PG: "UG and PG Education Details",
  "12TH": "12th / Diploma Education Details",
  "10TH": "10th Education Details",
};

const FIELD_LABELS = {
  full_name: "Full Name", email: "Email", contact_number: "Mobile Number",
  alternate_number: "Alternate Contact", date_of_birth: "Date of Birth", gender: "Gender",
  current_address: "Present/Communication Address", permanent_address: "Permanent Address",
  aadhaar_number: "Aadhaar Number", pan_number: "PAN Number",
  highest_qualification: "Highest Qualification", university_name: "University Name",
  graduation_year: "Graduation Year", bank_account_number: "Bank Account Number",
  bank_ifsc_code: "Bank IFSC Code", emergency_contact_name: "Emergency Contact Name",
  emergency_contact_number: "Emergency Contact Number",
  marital_status: "Marital Status", blood_group: "Blood Group",
  position_applied_for: "Position Applied For", skills_technologies: "Skill/Technologies Worked",
  alternate_email: "Alternate E-Mail ID", linkedin_link: "LinkedIn Page Link",
  any_backlogs: "Any Backlogs in the Education", source: "Source",
  worked_in_levelshift_before: "Worked in LevelShift Before",
  total_experience_yrs: "Total Experience (Yrs)", relevant_skill_exp_yrs: "Relevant Skill Exp. (Yrs)",
  current_ctc_lpa: "Current CTC (LPA)", expected_ctc_lpa: "Expected CTC (LPA)",
  additional_allowance: "Additional Allowance (Rs)", variable_comp: "Variable Comp (Rs)",
  notice_period_days: "Notice Period (Days)", other_offers: "Holds Other Offers",
  technical_certifications: "Technical Certifications",
  understanding_of_levelshift: "Understanding of LevelShift", aspirations: "Aspirations",
  declaration_accepted: "Declaration Accepted", declaration_place: "Declaration Place",
  declaration_date: "Declaration Date",
  hr_candidate_id: "HR: Candidate ID", hr_candidate_email: "HR: Candidate Email ID",
  profile_picture: "Candidate Profile Picture", signature: "Signature",
  // education / employment / reference columns
  qualification: "Qualification", course_college: "Course / College", cgpa_percent: "% CGPA",
  year_of_passing: "Year of Passing", has_marksheet: "Has Mark Sheet", gaps: "Gaps",
  company_name: "Company", position_held: "Position Held", from_date: "From", to_date: "To",
  currently_working: "Currently Working", reason_for_leaving: "Reason for Leaving",
  offer_letter: "Offer Letter", relieving_letter_status: "Relieving Letter",
  experience_certificate: "Experience Certificate",
  employee_name: "Employee Name", email_id: "Email ID", technology: "Technology", experience: "Experience",
  // BGV
  consent_bgv: "I authorise background verification",
  consent_criminal_check: "I consent to a criminal record check",
  may_contact_current_employer: "May we contact your current employer now?",
  name_as_per_records: "Full name as per government records",
  other_names_used: "Any other/former name used (maiden name, alias)",
  passport_number: "Passport Number",
  passport_expiry: "Passport Expiry",
  driving_licence_number: "Driving Licence Number",
  has_gaps: "Any gap of more than 60 days in education or employment?",
  ever_convicted: "Ever convicted of a criminal offence?",
  conviction_details: "Conviction details",
  pending_case: "Any pending court case or investigation?",
  pending_case_details: "Pending case details",
  ever_terminated: "Ever terminated or asked to resign?",
  termination_details: "Termination details",
  disciplinary_action: "Ever subject to disciplinary action?",
  disciplinary_details: "Disciplinary action details",
  has_bond_noncompete: "Under any bond or non-compete agreement?",
  bond_details: "Bond / non-compete details",
  dual_employment: "Currently hold any other employment?",
  dual_employment_details: "Other employment details",
  declaration_accepted: "Declaration accepted",
  declaration_place: "Place",
  declaration_date: "Date",
  signed_consent_form: "Signed BGV Consent Form",
  passport_copy_bgv: "Passport Copy",
  form16_last_year: "Form 16 / ITR — Last Year",
  form16_previous_year: "Form 16 / ITR — Previous Year",
  bank_statement_salary: "Bank Statement (salary credits, 3–6 months)",
  police_clearance_certificate: "Police Clearance Certificate (if available)",
  bgv_signature: "Signature",
  address_type: "Address Type",
  full_address: "Full Address",
  city: "City",
  state: "State",
  pin_code: "PIN Code",
  residence_type: "Residence Type",
  verifier_name: "Contact Person (for verification)",
  verifier_contact: "Contact Number",
  nearest_police_station: "Nearest Police Station",
  institution: "Institution",
  university_board: "University / Board",
  roll_number: "Roll / Enrollment No.",
  registration_number: "Registration No.",
  study_mode: "Mode of Study",
  verification_contact: "College Verification Contact",
  company_address: "Company Address",
  designation_joining: "Designation (at joining)",
  designation_leaving: "Designation (at leaving)",
  employment_type: "Employment Type",
  payroll_company: "Payroll Company (if third-party)",
  last_drawn_ctc: "Last Drawn CTC",
  manager_name: "Reporting Manager",
  manager_designation: "Manager Designation",
  manager_email: "Manager Email",
  manager_phone: "Manager Phone",
  hr_name: "HR Contact Name",
  hr_email: "HR Email",
  hr_phone: "HR Phone",
  eligible_for_rehire: "Eligible for Rehire?",
  may_contact_now: "May we contact now?",
  relationship: "Relationship",
  years_known: "Years Known",
  gap_type: "Gap Type",
  duration: "Duration",
  reason: "Reason",
  employee_id: "Employee ID",
  name: "Name", designation: "Designation", company: "Company", phone: "Phone",
  // Document Collection uploads
  // Document Collection uploads
  cc_offer_letter: "Current company — Offer Letter",
  cc_role_change_letter: "Current company — Role Change Letter",
  cc_experience_letter: "Current company — Experience Letter",
  cc_relieving_letter: "Current company — Relieving Letter",
  cc_pay_slips: "Current company — Last 3 Months Pay Slips",
  pc1_offer_letter: "Previous company 1 — Offer Letter",
  pc1_role_change_letter: "Previous company 1 — Role Change Letter",
  pc1_experience_letter: "Previous company 1 — Experience Letter",
  pc1_relieving_letter: "Previous company 1 — Relieving Letter",
  pc1_pay_slips: "Previous company 1 — Last 3 Months Pay Slips",
  pc2_offer_letter: "Previous company 2 — Offer Letter",
  pc2_role_change_letter: "Previous company 2 — Role Change Letter",
  pc2_experience_letter: "Previous company 2 — Experience Letter",
  pc2_relieving_letter: "Previous company 2 — Relieving Letter",
  pc2_pay_slips: "Previous company 2 — Last 3 Months Pay Slips",
  pc3_offer_letter: "Previous company 3 — Offer Letter",
  pc3_role_change_letter: "Previous company 3 — Role Change Letter",
  pc3_experience_letter: "Previous company 3 — Experience Letter",
  pc3_relieving_letter: "Previous company 3 — Relieving Letter",
  pc3_pay_slips: "Previous company 3 — Last 3 Months Pay Slips",
  pc4_offer_letter: "Previous company 4 — Offer Letter",
  pc4_role_change_letter: "Previous company 4 — Role Change Letter",
  pc4_experience_letter: "Previous company 4 — Experience Letter",
  pc4_relieving_letter: "Previous company 4 — Relieving Letter",
  pc4_pay_slips: "Previous company 4 — Last 3 Months Pay Slips",
  marksheet_10: "10th Marks Sheet", marksheet_12_diploma: "12th Marks Sheet / Diploma",
  ug_consolidated_marksheet: "UG – Consolidated Marksheet", ug_certificate: "UG Certificate",
  pg_consolidated_marksheet: "PG – Consolidated Marksheet", pg_certificate: "PG Certificate",
  other_edu_marksheet: "Other Educational Marksheet", other_edu_certificate: "Other Educational Certificate",
  additional_certifications: "Additional Certifications",
  passport_size_photo: "Passport Size Photo", pan_card: "Pan Card", aadhar_card: "Aadhar Card",
  passport_copy: "Passport Copy", address_proof: "Address Proof", id_proof: "ID Proof",
};

function labelFor(key) { return FIELD_LABELS[key] || key.replaceAll("_", " "); }
